### PR TITLE
[ WIP ] Sbom spdx

### PR DESCRIPTION
**Pull request by crosas-3p**
Instead of having this tool attached to a specific repo it'll be good to have a generic tool that can be used anywhere (local, from CI tool...) 

- Flags used are the same as the rest of the ecm tool
- Added the sbom linux binary into the /bin folder which is used by this feature for module manager only.
- The /build folder is handled by the go code (this is a point to discuss)
- Output format for SBOMs: SPDX specification

cmd: 
sbom-spdx -r rke2 -m v1.21.5 -p /absolute/path/to/repo/

Issue:
- [RKE2 498](https://github.com/rancher/rke2/issues/498)

### CODE REVIEW

**Comment by crosas-3p** [comment]
Here are the output files (zipped as GH doesn't allow .spdx format) 
[sbom-spdx-generated-files.zip](https://github.com/rancher/ecm-distro-tools/files/7997066/sbom-spdx-generated-files.zip)

**Comment by nikolaishields** [comment]
Is `NOASSERTION` the expected output for licensing information for all of the packages listed?

```
PackageName: github.com/rancher/rke2
SPDXID: SPDXRef-Package-github.com.rancher.rke2
PackageVersion: b5f56b3
PackageSupplier: Organization: github.com/rancher/rke2
PackageDownloadLocation: git+https://github.com/dereknola/rke2.git
FilesAnalyzed: false
PackageChecksum: SHA256: eb8d3f4013f1f114f0b58f214e7271c75a27b3f44741b0326418ebc64d554b4b
PackageHomePage: https://github.com/rancher/rke2
PackageLicenseConcluded: NOASSERTION
PackageLicenseDeclared: NOASSERTION
PackageCopyrightText: NOASSERTION
PackageLicenseComments: NOASSERTION
PackageComment: NOASSERTION
```

**Comment by crosas-3p** [comment]
> Is `NOASSERTION` the expected output for licensing information for all of the packages listed?
> 
> ```
> PackageName: github.com/rancher/rke2
> SPDXID: SPDXRef-Package-github.com.rancher.rke2
> PackageVersion: b5f56b3
> PackageSupplier: Organization: github.com/rancher/rke2
> PackageDownloadLocation: git+https://github.com/dereknola/rke2.git
> FilesAnalyzed: false
> PackageChecksum: SHA256: eb8d3f4013f1f114f0b58f214e7271c75a27b3f44741b0326418ebc64d554b4b
> PackageHomePage: https://github.com/rancher/rke2
> PackageLicenseConcluded: NOASSERTION
> PackageLicenseDeclared: NOASSERTION
> PackageCopyrightText: NOASSERTION
> PackageLicenseComments: NOASSERTION
> PackageComment: NOASSERTION
> ```

good call. the answer is No, at least not for the root package... im working on adding the Apache Licenses according to [SPDX license list](https://spdx.org/licenses/) but I need to find all licenses used in the files as shown in [License List in source files](https://spdx.dev/wp-content/uploads/sites/41/2020/04/using_spdx_license_list_short_identifiers.pdf).
Feel free to point out anything that seems odd

**Comment by nikolaishields** [comment]
@crosas-3p I don't think we need to build a tool to handle this. It would seem that there are a collection of utilities that do this already that are either in development or integrate into existing package managers/build tools to generate the required spdx document. Some even go so far as to detect the dependency relationships between the referenced libraries in the spdx output.

- https://github.com/opensbom-generator/spdx-sbom-generator
- https://github.com/spdx/spdx-build-tool

It would also seem that sbom generation would be best performed as part of a release job/stage in a cicd pipeline, with the resulting spdx file stored as a release artifact. Should these tools serve the need we can move forward without the maintenance burden of building a utility ourselves. I have some availability after 3PM tomorrow if you're game to hop on a call and hack on this.

**Comment by briandowns** [comment]
This will be completed as a byproduct of the SLSA work we're doing with RFed.

**Comment by crosas-3p** [comment]
[sbom-rke2-1.zip](https://github.com/rancher/ecm-distro-tools/files/8112839/sbom-rke2-1.zip)
generated SBOMs

**Pull request closed without merging**
