### PR TITLE
Weekly Report

### PR DESCRIPTION
**Pull request by briandowns**

### CODE REVIEW

**Review by nikolaishields — APPROVED** [review]
LGTM

**Review by brooksn — APPROVED** [review]
LGTM. HTML could be prettier if there are line breaks between issues, e.g.
```
#[{{$pr.GetNumber}}]({{$pr.GetHTMLURL}}) {{$pr.GetTitle}}  {{end}}
```

**Comment by briandowns** [comment]
@brooksn this is supposed to be Mardown. Do you think there'd be better formatting? I was trying to match the existing weekly report.

**Comment by brooksn** [comment]
@briandowns it looks fine as markdown.

**Pull request merged**
